#!/bin/bash

# wtf this is 
# this is a script to download & install Docker on Ubuntu 16.04 (Xenial)

# e => exit script if any command fails
# x => print every command before execution
set -ex

# installing curl if not already installed
if [ -z "$(which curl)" ]
then
  sudo apt-get update
  sudo apt-get -y install curl
fi

sudo apt-get update

sudo apt-key adv \
   --keyserver hkp://p80.pool.sks-keyservers.net:80 \
   --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \

sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' 

sudo apt-get update && apt-cache policy docker-engine

sudo apt-get install -y docker-engine

echo "Docker installed at : $(which docker)"

# installing docker compose
sudo curl -o /usr/local/bin/docker-compose \
     -L "https://github.com/docker/compose/releases/download/1.11.1/docker-compose-$(uname -s)-$(uname -m)"

sudo chmod +x /usr/local/bin/docker-compose

 
